### PR TITLE
introducing apm-server to elastdocker

### LINKED ISSUE #60: Add APM Server
**Describe the solution you'd like**
Add ELkStack APM Server 

**Additional context**

### PR DESCRIPTION
**Pull request by mostafahussein**
Signed-off-by: (╯°□°）╯︵ uᴉǝssnH ɐɟɐʇsoW <mostafa.hussein91@gmail.com>

What does this implement/fix? Explain your changes.
---------------------------------------------------
This PR will do the following:
- Add apm-server as a running container to the current stack
- Update kibana.yml with pre-configuration to add apm integration package and create a default policy for it

Does this close any currently open issues?
------------------------------------------
closes #60 

Any relevant logs, error output, etc?
-------------------------------------
No

Any other comments?
-------------------
The apm integration configured does not handle settings customization, not sure if it will be possible through API calls

Where has this been tested?
---------------------------
Ubuntu Server 22.04 LTS, verified by the points below:

- The stack is up and running
- Elastic APM integration automatically enabled on kibana
- Custom application using elastic-apm package while passing the CA certificate and secret token to be able to send events to the apm-server

### CODE REVIEW

**Comment by sherifabdlnaby** [comment]
@mostafahussein 
Impressive! Adding APM Server has been on the TODO list of this project for quite some time! Thank you for your contribution! 

Can you please add a section in README to explain how to Connect, Authenticate and Use the APM Server?

**Comment by mostafahussein** [comment]
Thank you @sherifabdlnaby .
Sure, will add a section for APM in the README file

**Comment by mostafahussein** [comment]
Hi @sherifabdlnaby ,
The README file got updated, please review it and let me know if there are any other modifications required.

**Comment by sherifabdlnaby** [comment]
@mostafahussein Thanks for your contribution! I added a small nitty change to move the APM Section to be before the Monitoring Part.

**Pull request merged**
